language: node_js
node_js:
    - "10"
services:
  - docker
stages:
  - test
  - name: documentation
    if: branch = master
  - name: build
    if: (branch = master OR branch = develop) AND type != pull_request
jobs:
  include:
    - stage: test
      script:
      - npm install typescript -g
      - npm run typecheck
      - npm run lint
      - npm run test
      - npm run codecov
    - stage: documentation
      script:
        - npm run docs
        - touch ./docs/.nojekyll
      deploy:
        provider: pages
        skip_cleanup: true
        github_token: $GITHUB_TOKEN
        local_dir: ./docs
        target_branch: gh-pages
        on:
          branch: master
    - stage: build
      script: docker build -t $TRAVIS_REPO_SLUG:$TRAVIS_BRANCH .
      deploy:
        provider: script
        script: bash docker_deploy.sh
