version: '3.7'

services:
  postgres:
    image: postgres:10.7
    ports:
      - "127.0.0.1:${DB_PORT}:${DB_PORT}"
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - "postgres_data:/var/lib/postgresql/data"
      - "./init-postgres-ssl.sh:/docker-entrypoint-initdb.d/init-ssl.sh"
    command: ["postgres", "-c", "ssl=on"]
  node:
    build:
      context: .
      target: base
      args:
        OPEN_PORT: ${SERVER_PORT}
    environment:
      - APP_NAME
      - CAS_URL
      - CLIENT_URL
      - PUBLIC_CLIENT_URL
      - DB_HOSTNAME
      - DB_PORT
      - DB_DATABASE
      - DB_USERNAME
      - DB_PASSWORD
      - REDIS_HOST
      - REDIS_PASSWORD
      - REDIS_PORT
      - REDIS_PREFIX
      - LOG_LEVEL
      - NODE_ENV
      - SERVER_URL
      - SERVER_PORT
      - SESSION_SECRET
      - HTTPS_ON
      - HTTPS_PRIVATE_KEY
      - HTTPS_PUBLIC_CERT
    user: "1000:1000"
    ports:
      - "127.0.0.1:${SERVER_PORT}:${SERVER_PORT}"
    volumes:
      - ".:/node:rw"
    command: ["npm", "run", "start:server"]
    links:
      - redis
      - postgres
    depends_on:
      - "postgres"
      - "redis"
  client:
    build:
      context: .
      target: base
      args:
        OPEN_PORT: ${CLIENT_PORT}
    environment:
      - APP_NAME
      - CLIENT_PORT
      - SERVER_URL
      - SERVER_PORT
      - PUBLIC_CLIENT_URL
    user: "1000:1000"
    ports:
      - "127.0.0.1:${CLIENT_PORT}:${CLIENT_PORT}"
    volumes:
      - ".:/node:rw"
    command: ["npm", "run", "start:client"]
  redis:
    image: bitnami/redis:6.2
    environment:
      - REDIS_PASSWORD
    ports:
      - "127.0.0.1:${REDIS_PORT}:${REDIS_PORT}"
    volumes:
      - "./init-redis-ssl.sh:/opt/bitnami/scripts/redis/init-redis-ssl.sh"
    command: /opt/bitnami/scripts/redis/init-redis-ssl.sh
volumes:
  postgres_data:
